[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "twitchlib"
version = "0.0.2"
authors = [{ name = "Negomir99" , email = "miloss.ned99@gmail.com" }]
description = "Lib for twitch requests"
dependencies=[
	"httpx"
]
